from app import app;
from models import db, Traveler;

with app.app_context():

    Traveler.query.delete()

    travelers = []
    travelers.append(Traveler(first_name="Ophillia", last_name="Clement", sprite_image="https://www.spriters-resource.com/resources/sheet_icons/111/113913.png?updated=1550610715", job="Cleric", game_origin="Octopath Traveler", quote="Till we meet again, dear sister. May the Sacred Flame light your path!", bio="Ophilia Clement is one of eight playable characters in Octopath Traveler. She is one of the sisters that work at the Church of Flamesgrace. Ophilia embarks on a pilgrimage to restore light to the realm in her adoptive sister's stead after Archbishop Josef falls seriously ill."))
    travelers.append(Traveler(first_name="Cyrus", last_name="Albright", sprite_image="https://www.spriters-resource.com/resources/sheet_icons/113/115984.png?updated=1555011008", job="Scholar", game_origin="Octopath Traveler", quote="A world of knowledge awaits.", bio="Cyrus Albright is one of eight playable characters in Octopath Traveler. He is a professor at the Royal Academy located in Atlasdam, found in the Flatlands. Cyrus is known for caring greatly about knowledge and his passion for teaching." ))
    travelers.append(Traveler(first_name="Tressa", last_name="Colzione", sprite_image="https://www.spriters-resource.com/resources/sheet_icons/113/116031.png?updated=1555072644", job="Merchant", game_origin="Octopath Traveler", quote="From the next chapter on, this will be my story.", bio="Tressa Colzione is one of eight playable characters in Octopath Traveler. She is the daughter of two merchants who created the Colzione Trading Shop in the port town Rippletide and is travelling throughout the realm of Orsterra as a traveling merchant."))
    travelers.append(Traveler(first_name="Olberic", last_name="Eisenberg", sprite_image="https://www.spriters-resource.com/resources/sheet_icons/113/116030.png?updated=1555072398", job="Warrior", game_origin="Octopath Traveler", quote="To what end do I swing my blade?", bio="Olberic Eisenberg is one of eight playable characters in Octopath Traveler. He was also one of the two playable characters in the Project Octopath Traveler Demo, the other being Primrose. A knight from a lost kingdom, Olberic became a sellsword and temporarily resided in Cobbleston. After a chance meeting with a colleague of his previous brother-in-arms, he decides to set out to find the answers he seeks— one of them as to why he swings his blade."))
    travelers.append(Traveler(first_name="Primrose", last_name="Azelhart", sprite_image="https://www.spriters-resource.com/resources/sheet_icons/113/116033.png?updated=1555072888", job="Dancer", game_origin="Octopath Traveler", quote="May I have this dance?", bio="Primrose Azelhart is one of the eight playable characters in Octopath Traveler. She was only one of the two playable characters in the Project Octopath Traveler Demo, the other being Olberic. Primrose was a member of the once proud House Azelhart, until one fateful night changed her life for the worse. Now, she takes the front of a dancer in Sunshade as a means to try and track down the men who instigated the murder against her father."))
    travelers.append(Traveler(first_name="Alfyn", last_name="Greengrass", sprite_image="https://www.spriters-resource.com/resources/sheet_icons/110/113459.png?updated=1548964674", job="Apothecary", game_origin="Octopath Traveler", quote="Sorry, my hand slipped.", bio="Alfyn Greengrass is one of eight playable characters in Octopath Traveler. He is a talented but inexperienced apothecary who is well-known within his home village of Clearbrook, but an unknown outside of it. After saving his friend's younger sister from the poison of a Blotted Viper, he goes on a journey to heal the sick and suffering, as well as to become more experienced in his profession so that he can help even more lives."))
    travelers.append(Traveler(first_name="Therion", sprite_image="https://www.spriters-resource.com/resources/sheet_icons/113/116032.png?updated=1555072735", job="Thief", game_origin="Octopath Traveler", quote="Like a thief in the night.", bio="Therion is one of eight playable characters in Octopath Traveler. He is a master thief known throughout the realm thanks to his multiple exploits in stealing. It is mentioned that almost no one knows of Therion's face despite his infamy and that he is the enemy of every wealthy home and person."))
    travelers.append(Traveler(first_name="H'aanit", sprite_image="https://www.spriters-resource.com/resources/sheet_icons/113/116029.png?updated=1555072483", job="Hunter", game_origin="Octopath Traveler", quote="Lives entwined, a tapestry woven anew each dawn, every thread a part of the whole.", bio="H'aanit is one of eight playable characters in Octopath Traveler. She is a hunter who resides in S'warkii and is one of the last descendants of the people who live in the forest. When her master, Z'aanta, goes missing, H'aanit sets out in search of him. She is always accompanied by her snow leopard companion, Linde."))

    db.session.add_all(travelers)
    db.session.commit()

    print("⚔️Successfully Seeded⚔️")