"""empty message

Revision ID: a7d099332060
Revises: 
Create Date: 2023-09-13 20:31:53.664277

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7d099332060'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('travelers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=25), nullable=False),
    sa.Column('last_name', sa.String(length=25), nullable=True),
    sa.Column('sprite_image', sa.String(), nullable=False),
    sa.Column('job', sa.String(), nullable=False),
    sa.Column('game_origin', sa.String(), nullable=False),
    sa.Column('quote', sa.String(), nullable=False),
    sa.Column('bio', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('first_name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('travelers')
    # ### end Alembic commands ###
